version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_RUN_HOST=0.0.0.0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
